### ISSUE TITLE
Mismatched types in music code examples

### ISSUE THREAD

**Issue by kkeri** [wipplelang/wipple#114]
On the **Making music** page the code examples don't run, except the first one. The problem is with the `note` commands, For example this one.

~~~
note "G4" ((1 / 2) beats)
~~~

`1 / 2` is highlighted in red and I get the following error message:

error: mismatched types
expected Number, but found Integer

Otherwise I love the playground. You did a good job!

**Comment by WilsonGramer** [comment]
Thanks for letting me know! It should be fixed in eb7c9034dd1ca8b22f3128124752bebe57e766bd.
