### ISSUE TITLE
Consider using nom for parsing

### ISSUE THREAD

**Issue by fenduru** [wipplelang/wipple#23]
https://docs.rs/nom/6.1.2/nom/

This is widely considered the best Rust parser library. I'd recommend it as it would remove a lot of the complexity from the parsing code.

**Comment by WilsonGramer** [comment]
Hey @fenduru! I'm not too experienced in parsing and just wanted something that worked when I initially wrote the parser, so I definitely agree it's overcomplicated. Would you like to take a stab at implementing it in nom? That would be much appreciated! 😄

**Comment by WilsonGramer** [comment]
@fenduru Let me know if you're interested in this! Otherwise I'm going to close it for now.
